/**
 * Standardized application-wide error codes.
 * Constant string codes allow the frontend to trigger specific UI logic without relying on fragile text messages.
 */
export enum ErrorCode {
  // Authentication & Session
  ERR_INVALID_CREDENTIALS = 'ERR_INVALID_CREDENTIALS',
  ERR_ACCOUNT_INACTIVE = 'ERR_ACCOUNT_INACTIVE',
  ERR_UNAUTHORIZED = 'ERR_UNAUTHORIZED',
  ERR_TOKEN_EXPIRED = 'ERR_TOKEN_EXPIRED',
  ERR_INVALID_TOKEN = 'ERR_INVALID_TOKEN',
  ERR_FORBIDDEN = 'ERR_FORBIDDEN',

  // Entitlements & Authorization
  ERR_INSUFFICIENT_PERMISSIONS = 'ERR_INSUFFICIENT_PERMISSIONS',
  ERR_INSUFFICIENT_TIER = 'ERR_INSUFFICIENT_TIER',

  // Domain & Resources
  ERR_USER_NOT_FOUND = 'ERR_USER_NOT_FOUND',
  ERR_RESOURCE_NOT_FOUND = 'ERR_RESOURCE_NOT_FOUND',
  ERR_EMAIL_ALREADY_EXISTS = 'ERR_EMAIL_ALREADY_EXISTS',
  ERR_RESOURCE_CONFLICT = 'ERR_RESOURCE_CONFLICT',
  ERR_SUBSCRIPTION_NOT_FOUND = 'ERR_SUBSCRIPTION_NOT_FOUND',

  // Validation & Input
  ERR_VALIDATION_FAILED = 'ERR_VALIDATION_FAILED',
  ERR_BAD_REQUEST = 'ERR_BAD_REQUEST',

  // Database & System
  ERR_DATABASE_ERROR = 'ERR_DATABASE_ERROR',
  ERR_INTERNAL_SERVER_ERROR = 'ERR_INTERNAL_SERVER_ERROR',
  ERR_SERVICE_UNAVAILABLE = 'ERR_SERVICE_UNAVAILABLE',
}
